"""arifosmcp.core.physics.economic_invariants — Re-export wrapper.

CANONICAL SOURCE: core/physics/economic_invariants.py
This file exists so that arifosmcp.core.physics.* imports resolve correctly.
All logic lives in the canonical copy. Do NOT edit this file — edit the
canonical copy and this re-export will pick up changes automatically.
"""
from __future__ import annotations

from core.physics.economic_invariants import (
    EconomicInvariantError,
    MaintenanceScalingError,
    check_maintenance_scaling,
    run_all_invariants,
)

__all__ = [
    "EconomicInvariantError",
    "MaintenanceScalingError",
    "check_maintenance_scaling",
    "run_all_invariants",
]
