"""
arifosmcp.core.physics.institutional_evolution — Re-export wrapper.

CANONICAL SOURCE: core/physics/institutional_evolution.py
This file exists so that arifosmcp.core.physics.* imports resolve correctly.
All logic lives in the canonical copy. Do NOT edit this file — edit the
canonical copy and this re-export will pick up changes automatically.

If this import fails, the federation cannot enforce Invariant #15.
"""
from __future__ import annotations

# Re-export everything from the canonical module
from core.physics.institutional_evolution import (
    # Exception types
    SuccessionError,
    InstitutionalEvolutionError,
    AttentionBudgetExceededError,
    PopulationAbsorptionError,
    SuccessionContinuityError,
    AIAdaptationRateExceededError,
    ConstitutionalRejectionError,
    # Function API
    check_human_attention_budget,
    check_institutional_succession,
    check_ai_adaptation_rate,
    check_population_absorption,
    check_institutional_evolution,
    # Guard class
    InstitutionalEvolutionGuard,
)

__all__ = [
    "SuccessionError",
    "InstitutionalEvolutionError",
    "AttentionBudgetExceededError",
    "PopulationAbsorptionError",
    "SuccessionContinuityError",
    "AIAdaptationRateExceededError",
    "ConstitutionalRejectionError",
    "check_human_attention_budget",
    "check_institutional_succession",
    "check_ai_adaptation_rate",
    "check_population_absorption",
    "check_institutional_evolution",
    "InstitutionalEvolutionGuard",
]
