"""conftest.py — pytest hooks for adversarial baseline report generation.

Auto-picked up by pytest. Writes baseline_report.{json,md} at session end
based on the _RESULTS list accumulated in test_mcp_adversarial_baseline.py.
"""
import os
import sys
import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path

REPORT_DIR = Path("/root/arifOS/tests/reports")

# We collect into the test module's module-level _RESULTS list
# Import that to read the results at session finish
def pytest_sessionfinish(session, exitstatus):
    """Called by pytest at end of session — generates the baseline report."""
    try:
        # Find the test module (pytest registers it as "tests.<name>" when conftest
        # is in the tests/ dir; but the registered name varies)
        import sys as _sys
        candidates = [k for k, v in _sys.modules.items() if hasattr(v, "_RESULTS") and getattr(v, "_RESULTS", None)]
        # Remove the debug print in the final version
        if not candidates:
            print("[conftest] no module with _RESULTS found", file=_sys.stderr)
            return
        test_module = _sys.modules[candidates[0]]
        if test_module is None:  # never reached, but kept for safety
            print("[conftest] test_mcp_adversarial_baseline not loaded, skipping report", file=sys.stderr)
            return
        results = getattr(test_module, "_RESULTS", [])
        if not results:
            print("[conftest] _RESULTS empty, skipping report", file=sys.stderr)
            return
        # Get git commit
        try:
            gc = subprocess.check_output(
                ["git", "rev-parse", "HEAD"],
                cwd="/root/arifOS", stderr=subprocess.DEVNULL, timeout=5
            ).decode().strip()
        except Exception:
            gc = "unknown"
        ts = datetime.now(timezone.utc).isoformat()
        # Build report
        report = {
            "report_id": f"MCP-ADVERSARIAL-BASELINE-{ts.replace(':', '').replace('-', '')[:15]}",
            "generated_at": ts, "git_commit": gc,
            "spec": "ARIFOS-TEST-SPEC-v1 (F13-ratified, 2026-10-05)",
            "test_count": len(results),
            "results": results,
            "summary": {
                "pass": sum(1 for r in results if r["verdict"] == "PASS"),
                "fail": sum(1 for r in results if r["verdict"] == "FAIL"),
                "inconclusive": sum(1 for r in results if r["verdict"] == "INCONCLUSIVE"),
            },
            "design_gaps": [r for r in results if r.get("design_gap")],
            "security_breaches": [r for r in results if r.get("security_breach")],
        }
        REPORT_DIR.mkdir(parents=True, exist_ok=True)
        json_path = REPORT_DIR / "baseline_report.json"
        json_path.write_text(json.dumps(report, indent=2, ensure_ascii=False))
        # MD
        md = [
            "# MCP Adversarial Baseline Report",
            "", f"- **Generated:** {ts}", f"- **Git commit:** `{gc}`",
            "- **Spec:** ARIFOS-TEST-SPEC-v1 (F13-ratified, 2026-10-05)",
            f"- **Tests run:** {len(results)}",
            f"- **PASS:** {report['summary']['pass']}",
            f"- **FAIL:** {report['summary']['fail']}",
            f"- **INCONCLUSIVE:** {report['summary']['inconclusive']}",
            "", "## Decision table", "",
            "| Test ID | Name | Expected | Actual Reason | Verdict |",
            "|---------|------|----------|----------------|---------|",
        ]
        for r in results:
            actual = r["actual_reason"].replace("|", "\\|")[:200]
            md.append(f"| {r['test_id']} | {r['name']} | {r['expected']} | {actual} | {r['verdict']} |")
        md.append("")
        md.append("## Design gaps (NOT security breaches — to be addressed at spec/contract level)")
        md.append("")
        gaps = [r for r in results if r.get("design_gap")]
        if gaps:
            for r in gaps:
                md.append(f"- **Test {r['test_id']}** ({r['name']}): {r['design_gap']}")
        else:
            md.append("- (none)")
        md.append("")
        md.append("## Security breaches (must be fixed before production)")
        md.append("")
        breaches = [r for r in results if r.get("security_breach")]
        if breaches:
            for r in breaches:
                md.append(f"- **Test {r['test_id']}** ({r['name']}): {r['security_breach']}")
        else:
            md.append("- (none)")
        md.append("")
        md.append("---")
        md.append("_Generated by conftest.py · 2026-10-05_")
        md_path = REPORT_DIR / "baseline_report.md"
        md_path.write_text("\n".join(md))
        print(f"\n=== BASELINE REPORT WRITTEN ===", file=sys.stderr)
        print(f"  JSON: {json_path}", file=sys.stderr)
        print(f"  MD:   {md_path}", file=sys.stderr)
        print(f"  Summary: PASS={report['summary']['pass']} FAIL={report['summary']['fail']} INCONCLUSIVE={report['summary']['inconclusive']}", file=sys.stderr)
    except Exception as e:
        print(f"[conftest] sessionfinish error: {type(e).__name__}: {e}", file=sys.stderr)
        import traceback
        traceback.print_exc(file=sys.stderr)
