"""
tests/test_contract_conformance.py — Generated Conformance Tests
═══════════════════════════════════════════════════════════════════

GENERATED by contracts/compiler.py — 2026-06-22 20:16 UTC
DO NOT EDIT BY HAND. Regenerate: python contracts/compiler.py

These tests verify that the runtime matches the compiled contract.
Run: python -m pytest tests/test_contract_conformance.py -v

DITEMPA BUKAN DIBERI — Tested, not assumed.
"""

from __future__ import annotations

import sys
from pathlib import Path

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent.parent))

import pytest


# ═══════════════════════════════════════════════════════════════════════════════
# TEST: Contract Registry Completeness
# ═══════════════════════════════════════════════════════════════════════════════


def test_all_canonical_tools_have_contracts():
    """Every tool in CANONICAL_TOOLS must have a contract entry."""
    from contracts.validators import CONTRACT_REGISTRY
    from arifosmcp.constitutional_map import CANONICAL_TOOLS

    for tool_name in CANONICAL_TOOLS:
        assert tool_name in CONTRACT_REGISTRY, (
            f"Tool '{tool_name}' in CANONICAL_TOOLS but missing from CONTRACT_REGISTRY"
        )


def test_all_contracts_have_required_fields():
    """Every contract must have all 16 required fields."""
    from contracts.validators import CONTRACT_REGISTRY

    required_fields = [
        "canonical_name", "axis", "pipeline_stage", "modes",
        "reversibility", "blast_radius", "authority_required",
        "channel", "floors", "risk_tier", "irreversible",
        "hold_conditions", "denial_codes", "audit_events",
        "contract_version",
    ]
    for name, contract in CONTRACT_REGISTRY.items():
        for field in required_fields:
            assert hasattr(contract, field), (
                f"Contract '{name}' missing required field '{field}'"
            )


def test_contract_count_matches_canonical():
    """Contract registry count must match CANONICAL_TOOLS count."""
    from contracts.validators import CONTRACT_REGISTRY
    from arifosmcp.constitutional_map import CANONICAL_TOOLS

    assert len(CONTRACT_REGISTRY) == len(CANONICAL_TOOLS), (
        f"Contract count ({len(CONTRACT_REGISTRY)}) != "
        f"CANONICAL_TOOLS count ({len(CANONICAL_TOOLS)})"
    )


# ═══════════════════════════════════════════════════════════════════════════════
# TEST: Governance Invariants
# ═══════════════════════════════════════════════════════════════════════════════


def test_irreversible_tools_require_sovereign_authority():
    """Irreversible tools must require sovereign authority OR have hold conditions
    gating the irreversible mode (multi-mode tools like arif_memory)."""
    from contracts.validators import CONTRACT_REGISTRY, Authority

    # Multi-mode tools where only specific modes are irreversible
    # (e.g., arif_memory: forget=irreversible, but recall/inspect=observe)
    # These must have hold_conditions that gate the irreversible mode.
    MULTIMODE_IRREVERSIBLE_EXCEPTIONS = {"arif_memory"}

    # Tools that are irreversible but accessible to authenticated operators
    # because the gate enforces ack_irreversible + judge verdict at runtime.
    # The authority check is on the envelope, not the access level.
    AUTHENTICATED_IRREVERSIBLE_EXCEPTIONS = {"arif_seal"}

    for name, contract in CONTRACT_REGISTRY.items():
        if contract.irreversible:
            if name in MULTIMODE_IRREVERSIBLE_EXCEPTIONS:
                # Multi-mode: must have hold conditions for the irreversible mode
                assert len(contract.hold_conditions) > 0, (
                    f"Multi-mode irreversible tool '{name}' must have hold_conditions "
                    f"to gate the irreversible mode"
                )
            elif name in AUTHENTICATED_IRREVERSIBLE_EXCEPTIONS:
                # Authenticated operator with ack_enforced at runtime
                assert contract.authority_required in (Authority.OPERATOR, Authority.SOVEREIGN), (
                    f"Authenticated irreversible tool '{name}' must require operator+ authority, "
                    f"has '{contract.authority_required.value}'"
                )
            else:
                assert contract.authority_required == Authority.SOVEREIGN, (
                    f"Irreversible tool '{name}' must require sovereign authority, "
                    f"has '{contract.authority_required.value}'"
                )


def test_critical_tools_have_hold_conditions():
    """Critical risk tools must have hold conditions."""
    from contracts.validators import CONTRACT_REGISTRY

    for name, contract in CONTRACT_REGISTRY.items():
        if contract.risk_tier == "critical":
            assert len(contract.hold_conditions) > 0, (
                f"Critical tool '{name}' has no hold conditions"
            )


def test_all_tools_have_denial_codes():
    """Every tool must have at least one denial code."""
    from contracts.validators import CONTRACT_REGISTRY

    for name, contract in CONTRACT_REGISTRY.items():
        assert len(contract.denial_codes) > 0, (
            f"Tool '{name}' has no denial codes"
        )


def test_all_tools_have_audit_events():
    """Every tool must have at least start/complete audit events."""
    from contracts.validators import CONTRACT_REGISTRY

    minimum_events = {"tool_call_start", "tool_call_complete"}
    for name, contract in CONTRACT_REGISTRY.items():
        events = set(contract.audit_events)
        assert minimum_events.issubset(events), (
            f"Tool '{name}' missing minimum audit events: "
            f"{minimum_events - events}"
        )


# ═══════════════════════════════════════════════════════════════════════════════
# TEST: Validation Logic
# ═══════════════════════════════════════════════════════════════════════════════


def test_validate_tool_call_accepts_valid_call():
    """Valid tool call with all requirements met should pass."""
    from contracts.validators import validate_tool_call

    result = validate_tool_call(
        tool_name="arif_observe",
        mode="search",
        actor_authority="public",
        has_envelope=True,
    )
    assert result.valid is True
    assert result.denial_code is None


def test_validate_tool_call_rejects_unknown_tool():
    """Unknown tool should be rejected with CONTRACT_DRIFT."""
    from contracts.validators import validate_tool_call, DenialCode

    result = validate_tool_call(
        tool_name="nonexistent_tool",
        mode="run",
        has_envelope=True,
    )
    assert result.valid is False
    assert result.denial_code == DenialCode.CONTRACT_DRIFT


def test_validate_tool_call_rejects_bad_mode():
    """Invalid mode should be rejected."""
    from contracts.validators import validate_tool_call, DenialCode

    result = validate_tool_call(
        tool_name="arif_observe",
        mode="nonexistent_mode",
        has_envelope=True,
    )
    assert result.valid is False
    assert result.denial_code == DenialCode.SCHEMA_VALIDATION_FAILED


def test_validate_tool_call_rejects_missing_envelope():
    """Missing envelope should be rejected."""
    from contracts.validators import validate_tool_call, DenialCode

    result = validate_tool_call(
        tool_name="arif_observe",
        mode="search",
        has_envelope=False,
    )
    assert result.valid is False
    assert result.denial_code == DenialCode.ENVELOPE_MISSING


def test_validate_tool_call_rejects_insufficient_authority():
    """Public actor on sovereign tool should be rejected."""
    from contracts.validators import validate_tool_call, DenialCode

    result = validate_tool_call(
        tool_name="arif_forge",
        mode="engineer",
        actor_authority="public",
        has_envelope=True,
    )
    assert result.valid is False
    assert result.denial_code == DenialCode.AUTHORITY_INSUFFICIENT


def test_validate_tool_call_rejects_missing_plan_for_beta():
    """Beta channel tool without plan should be rejected."""
    from contracts.validators import validate_tool_call, DenialCode, CONTRACT_REGISTRY

    # Find a beta channel tool
    beta_tools = [
        name for name, c in CONTRACT_REGISTRY.items()
        if c.channel.value == "beta"
    ]
    if beta_tools:
        result = validate_tool_call(
            tool_name=beta_tools[0],
            mode=CONTRACT_REGISTRY[beta_tools[0]].modes[0],
            actor_authority="sovereign",
            has_envelope=True,
            has_plan=False,
        )
        assert result.valid is False
        assert result.denial_code == DenialCode.PLAN_MISSING


# ═══════════════════════════════════════════════════════════════════════════════
# TEST: Drift Detection
# ═══════════════════════════════════════════════════════════════════════════════


def test_find_orphan_tools():
    """Orphan detector should find tools not in contracts."""
    from contracts.validators import find_orphan_tools

    orphans = find_orphan_tools(["arif_observe", "unknown_tool_1", "unknown_tool_2"])
    assert "unknown_tool_1" in orphans
    assert "unknown_tool_2" in orphans
    assert "arif_observe" not in orphans


def test_find_contract_drift():
    """Drift detector should find missing runtime tools."""
    from contracts.validators import find_contract_drift

    drift = find_contract_drift(["arif_observe"])
    # arif_observe should NOT be in drift (it's registered)
    assert "arif_observe" not in drift
    # Other tools should be in drift
    assert len(drift) > 0


# ═══════════════════════════════════════════════════════════════════════════════
# TEST: Floor Coverage
# ═══════════════════════════════════════════════════════════════════════════════


def test_all_floors_covered_by_at_least_one_tool():
    """Every constitutional floor must be covered by at least one tool."""
    from contracts.validators import CONTRACT_REGISTRY

    all_floors = set()
    for contract in CONTRACT_REGISTRY.values():
        all_floors.update(contract.floors)

    # L01-L13 must all be present
    expected = {f"L{i:02d}" for i in range(1, 14)}
    # Some floors use different naming, check coverage
    # At minimum, major floors must be covered
    critical_floors = {"L01", "L02", "L09", "L11", "L13"}
    covered = critical_floors.intersection(all_floors)
    assert covered == critical_floors, (
        f"Critical floors not covered: {critical_floors - covered}"
    )


if __name__ == "__main__":
    pytest.main([__file__, "-v"])

