server {
    listen 80;
    server_name arif-fazil.com;
    location / {
        root /usr/share/nginx/html/arif;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    server_name aaa.arif-fazil.com;
    location / {
        root /usr/share/nginx/html/aaa;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    server_name forge.arif-fazil.com;
    location / {
        root /usr/share/nginx/html/forge;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    server_name waw.arif-fazil.com;
    location / {
        root /usr/share/nginx/html/waw;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    server_name apex.arif-fazil.com;
    location / {
        root /usr/share/nginx/html/apex;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    server_name wiki.arif-fazil.com;
    location / {
        root /usr/share/nginx/html/wiki;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    server_name geox.arif-fazil.com;
    location / {
        root /usr/share/nginx/html/geox;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    server_name arifos.arif-fazil.com arifOS.arif-fazil.com;
    location / {
        root /usr/share/nginx/html/arifos;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
