"""
arifOS Constitutional Kernel — Authority Gate
═══════════════════════════════════════════════

Enforces L13 Sovereign Overrides and Authority Binding.
Ensures irreversible actions require human-validated proof.

Hardened 2026-08-02 (F13 SOVEREIGN directive): Al-Kahf privilege boundary.
Added 3 enforcement fields to AuthorityProof:
  - requires_residue_only: agent sees residue, not intent
  - niat_holder: sovereign identity holding intent
  - sabar_mode: patience enforcement prevents over-interrogation

DITEMPA BUKAN DIBERI — Forged, Not Given
"""

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel

from arifosmcp.core.law_evaluator import FloorEvaluator
from arifosmcp.core.niat_guard import NiatVerdict, check_niat_claim
from arifosmcp.core.threat_engine import ThreatAssessment

# Al-Kahf privilege boundary constants (forged 2026-08-02)
NIAT_HOLDER_DEFAULT: str = "F13_SOVEREIGN"  # Sovereign holds niat (intent)
EPISTEMIC_LABEL_KAHF: str = "INT (interpretive mapping) · PLAUSIBLE"
AL_KAHF_RATIFIED_BY: str = "F13 SOVEREIGN (Muhammad Arif bin Fazil, 888)"
AL_KAHF_RATIFIED_AT_UTC: str = "2026-08-02T09:08:00Z"


class WitnessType(Enum):
    AI = "ai"
    HUMAN = "human"
    MULTI = "multi"


class AuthorityProof(BaseModel):
    authorized: bool = False
    requires_human: bool = False
    witness_type: WitnessType = WitnessType.AI
    plan_approved: bool = False
    reason: str = ""
    # ── Al-Kahf privilege boundary (forged 2026-08-02) ───────────────────
    # Framework reads residue, sovereign holds niat. Agent acts with sabar,
    # not interrogation. F13 SOVEREIGN = the niat holder.
    requires_residue_only: bool = True  # agent sees output, NOT intent
    niat_holder: str = NIAT_HOLDER_DEFAULT
    sabar_mode: bool = True  # patience enforcement prevents over-questioning
    al_kahf_ratified_by: str = AL_KAHF_RATIFIED_BY
    al_kahf_ratified_at_utc: str = AL_KAHF_RATIFIED_AT_UTC
    al_kahf_epistemic_label: str = EPISTEMIC_LABEL_KAHF


class AuthorityGate:
    """
    Authority is not a flag. It is a proof generated by this gate.
    """

    @classmethod
    def verify(cls, context: Any, threat: ThreatAssessment, floors: Any = None) -> AuthorityProof:
        requires_human = FloorEvaluator._requires_human_witness(context, threat)

        plan_approved = False
        if context.tool_name in {"arif_forge", "arif_forge_execute"} and context.mode in {
            "engineer",
            "write",
            "generate",
        }:
            if getattr(context, "plan_id", None) and context.plan_id in getattr(
                context, "plan_registry", set()
            ):
                plan_approved = True
            else:
                return AuthorityProof(
                    authorized=False,
                    requires_human=True,
                    reason="Forge requires approved plan_id (H2 ratification)",
                )

        if requires_human and getattr(context, "witness_type", WitnessType.AI) != WitnessType.HUMAN:
            return AuthorityProof(
                authorized=False,
                requires_human=True,
                witness_type=getattr(context, "witness_type", WitnessType.AI),
                reason="L13 SOVEREIGN: human witness required",
            )

        # ── Al-Kahf Privilege Boundary (forged 2026-08-02) ──────────────────
        # Consult NiatClaimGuard before returning authorized=True. Any artifact
        # that claims to know sovereign intent → CAUTION/VOID. The boundary is
        # runtime refusal, not a declaration — checked here on every verify().
        artifact_text = getattr(context, "artifact_text", "") or ""
        niat_result = check_niat_claim(
            artifact_text,
            requires_residue_only=True,
            sabar_mode=True,
            niat_holder=NIAT_HOLDER_DEFAULT,
        )
        if niat_result.verdict == NiatVerdict.VOID:
            return AuthorityProof(
                authorized=False,
                requires_human=True,
                reason=(
                    f"Al-Kahf boundary: VOID — claim of knowing intent "
                    f"(pattern={niat_result.trigger_pattern!r}, "
                    f"match={niat_result.matched_text!r})"
                ),
            )
        if niat_result.verdict == NiatVerdict.CAUTION:
            # Surface CAUTION — still authorized but flag in reason for audit.
            return AuthorityProof(
                authorized=True,
                requires_human=requires_human,
                plan_approved=plan_approved,
                reason=(
                    f"Al-Kahf sabar_mode: CAUTION "
                    f"({niat_result.trigger_pattern!r}); "
                    f"residue_only_preserved=False"
                ),
            )

        return AuthorityProof(
            authorized=True,
            requires_human=requires_human,
            plan_approved=plan_approved,
            reason="Authority verified",
        )
