"""
contracts/validators.py — Generated Runtime Validators
═══════════════════════════════════════════════════════

GENERATED by contracts/compiler.py — 2026-06-22 20:16 UTC
DO NOT EDIT BY HAND. Regenerate: python contracts/compiler.py

These validators enforce tool contracts at runtime.
Import and use in pre_execution_gate and tool dispatch.

DITEMPA BUKAN DIBERI — Validated, not trusted.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum
from typing import Any


# ═══════════════════════════════════════════════════════════════════════════════
# CONTRACT ENUMS
# ═══════════════════════════════════════════════════════════════════════════════


class Channel(StrEnum):
    STABLE = "stable"
    BETA = "beta"
    SANDBOX = "sandbox"


class Reversibility(StrEnum):
    REVERSIBLE = "reversible"
    GUARDED = "guarded"
    IRREVERSIBLE = "irreversible"


class BlastRadius(StrEnum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CIVILIZATIONAL = "civilizational"


class Authority(StrEnum):
    PUBLIC = "public"
    OPERATOR = "operator"
    SOVEREIGN = "sovereign"


class DenialCode(StrEnum):
    FLOOR_HARD_FAIL = "FLOOR_HARD_FAIL"
    AUTH_MISSING = "AUTH_MISSING"
    PLAN_MISSING = "PLAN_MISSING"
    PLAN_NOT_APPROVED = "PLAN_NOT_APPROVED"
    CONTRACT_DRIFT = "CONTRACT_DRIFT"
    WITNESS_DEFICIT = "WITNESS_DEFICIT"
    ONTOLOGY_VIOLATION = "ONTOLOGY_VIOLATION"
    TRUTH_DEFICIT = "TRUTH_DEFICIT"
    IRREVERSIBLE_WITHOUT_HOLD = "IRREVERSIBLE_WITHOUT_HOLD"
    CHANNEL_VIOLATION = "CHANNEL_VIOLATION"
    AUTHORITY_INSUFFICIENT = "AUTHORITY_INSUFFICIENT"
    BLAST_RADIUS_EXCEEDED = "BLAST_RADIUS_EXCEEDED"
    LEASE_EXPIRED = "LEASE_EXPIRED"
    EPOCH_MISMATCH = "EPOCH_MISMATCH"
    ENVELOPE_MISSING = "ENVELOPE_MISSING"
    VERDICT_TOKEN_MISSING = "VERDICT_TOKEN_MISSING"
    SCHEMA_VALIDATION_FAILED = "SCHEMA_VALIDATION_FAILED"
    HALLUCINATION_DETECTED = "HALLUCINATION_DETECTED"
    CONSCIOUSNESS_CLAIM = "CONSCIOUSNESS_CLAIM"
    HUMAN_VETO_REQUIRED = "HUMAN_VETO_REQUIRED"


# ═══════════════════════════════════════════════════════════════════════════════
# TOOL CONTRACT VALIDATOR
# ═══════════════════════════════════════════════════════════════════════════════


@dataclass(frozen=True)
class ToolContract:
    """Machine-readable contract for a single canonical tool."""
    canonical_name: str
    axis: str
    pipeline_stage: str
    modes: tuple[str, ...]
    reversibility: Reversibility
    blast_radius: BlastRadius
    authority_required: Authority
    channel: Channel
    floors: tuple[str, ...]
    risk_tier: str
    irreversible: bool
    hold_conditions: tuple[str, ...]
    denial_codes: tuple[str, ...]
    audit_events: tuple[str, ...]
    contract_version: str

    def allows_mode(self, mode: str) -> bool:
        """Check if this tool allows the given mode."""
        return mode in self.modes

    def requires_plan(self) -> bool:
        """Whether this tool requires an approved plan."""
        return self.channel in (Channel.BETA, Channel.SANDBOX) or self.risk_tier in ("high", "critical")

    def requires_verdict_token(self) -> bool:
        """Whether this tool requires a judge verdict token."""
        return self.risk_tier in ("high", "critical")

    def check_authority(self, actor_authority: Authority) -> bool:
        """Check if actor authority meets tool requirement."""
        order = {Authority.PUBLIC: 0, Authority.OPERATOR: 1, Authority.SOVEREIGN: 2}
        return order.get(actor_authority, -1) >= order.get(self.authority_required, 999)



# ═══════════════════════════════════════════════════════════════════════════════
# CONTRACT REGISTRY — all 21 canonical tools
# ═══════════════════════════════════════════════════════════════════════════════

CONTRACT_REGISTRY: dict[str, ToolContract] = {
    "arif_bridge_connect": ToolContract(
        canonical_name="arif_bridge_connect",
        axis="boundary",
        pipeline_stage="555",
        modes=("connect",),
        reversibility=Reversibility.REVERSIBLE,
        blast_radius=BlastRadius.MEDIUM,
        authority_required=Authority.OPERATOR,
        channel=Channel.STABLE,
        floors=("L01", "L11", "L10",),
        risk_tier="medium",
        irreversible=False,
        hold_conditions=("action_is_irreversible_without_human_ack", "actor_unverified_for_authenticated_action", "ontology_category_mismatch",),
        denial_codes=("CONSCIOUSNESS_CLAIM", "CONTRACT_DRIFT", "ENVELOPE_MISSING", "F10_ONTOLOGY_VIOLATION", "F11_AUTH_MISSING",),
        audit_events=("tool_call_complete", "tool_call_start",),
        contract_version="2026.06.22",
    ),
    "arif_compose": ToolContract(
        canonical_name="arif_compose",
        axis="reflect",
        pipeline_stage="444r",
        modes=("compose", "summarize", "cite", "tone_shift",),
        reversibility=Reversibility.REVERSIBLE,
        blast_radius=BlastRadius.LOW,
        authority_required=Authority.PUBLIC,
        channel=Channel.STABLE,
        floors=("L02", "L04", "L06", "L09",),
        risk_tier="low",
        irreversible=False,
        hold_conditions=("c_dark_above_0.30", "dignity_preservation_below_0.70", "evidence_quality_below_0.95", "output_increases_entropy",),
        denial_codes=("CONTRACT_DRIFT", "C_DARK_EXCEEDED", "DIGNITY_BREACH", "ENTROPY_INCREASE", "ENVELOPE_MISSING",),
        audit_events=("draft_created", "tool_call_complete", "tool_call_start",),
        contract_version="2026.06.22",
    ),
    "arif_critique": ToolContract(
        canonical_name="arif_critique",
        axis="critique",
        pipeline_stage="666",
        modes=("critique", "simulate", "redteam", "maruah", "deescalate", "empathy",),
        reversibility=Reversibility.REVERSIBLE,
        blast_radius=BlastRadius.MEDIUM,
        authority_required=Authority.PUBLIC,
        channel=Channel.STABLE,
        floors=("L05", "L06", "L09",),
        risk_tier="medium",
        irreversible=False,
        hold_conditions=("c_dark_above_0.30", "dignity_preservation_below_0.70", "peace_score_below_1.0",),
        denial_codes=("CONTRACT_DRIFT", "C_DARK_EXCEEDED", "DIGNITY_BREACH", "ENVELOPE_MISSING", "ESCALATION_DETECTED",),
        audit_events=("reasoning_trace", "tool_call_complete", "tool_call_start",),
        contract_version="2026.06.22",
    ),
    "arif_explore": ToolContract(
        canonical_name="arif_explore",
        axis="explore",
        pipeline_stage="111",
        modes=("navigator", "prospector", "driller", "mapper", "surveyor", "scout", "eureka", "auto",),
        reversibility=Reversibility.REVERSIBLE,
        blast_radius=BlastRadius.LOW,
        authority_required=Authority.PUBLIC,
        channel=Channel.STABLE,
        floors=("L02", "L07", "L04", "L09",),
        risk_tier="low",
        irreversible=False,
        hold_conditions=("c_dark_above_0.30", "evidence_quality_below_0.95", "output_increases_entropy", "uncertainty_band_outside_0.03_0.05",),
        denial_codes=("CONTRACT_DRIFT", "C_DARK_EXCEEDED", "ENTROPY_INCREASE", "ENVELOPE_MISSING", "EVIDENCE_INSUFFICIENT",),
        audit_events=("tool_call_complete", "tool_call_start",),
        contract_version="2026.06.22",
    ),
    "arif_fetch": ToolContract(
        canonical_name="arif_fetch",
        axis="verify",
        pipeline_stage="222",
        modes=("fetch", "search", "eureka",),
        reversibility=Reversibility.REVERSIBLE,
        blast_radius=BlastRadius.MEDIUM,
        authority_required=Authority.PUBLIC,
        channel=Channel.STABLE,
        floors=("L02", "L03", "L05", "L12",),
        risk_tier="medium",
        irreversible=False,
        hold_conditions=("evidence_quality_below_0.95", "injection_probability_above_0.85", "peace_score_below_1.0", "witness_score_below_0.75",),
        denial_codes=("CONSENSUS_UNMET", "CONTRACT_DRIFT", "ENVELOPE_MISSING", "ESCALATION_DETECTED", "EVIDENCE_INSUFFICIENT",),
        audit_events=("tool_call_complete", "tool_call_start",),
        contract_version="2026.06.22",
    ),
    "arif_forge": ToolContract(
        canonical_name="arif_forge",
        axis="execute",
        pipeline_stage="010",
        modes=("engineer", "query", "write", "generate", "commit", "recall", "dry_run",),
        reversibility=Reversibility.IRREVERSIBLE,
        blast_radius=BlastRadius.CIVILIZATIONAL,
        authority_required=Authority.SOVEREIGN,
        channel=Channel.BETA,
        floors=("L01", "L11", "L13",),
        risk_tier="critical",
        irreversible=True,
        hold_conditions=("action_is_irreversible_without_human_ack", "actor_unverified_for_authenticated_action", "missing_verdict_token", "plan_not_approved", "sovereign_approval_missing_for_irreversible",),
        denial_codes=("CONTRACT_DRIFT", "ENVELOPE_MISSING", "F11_AUTH_MISSING", "F13_SOVEREIGN_OVERRIDE", "F1_AMANAH_VIOLATION",),
        audit_events=("governance_checkpoint", "human_ack_verified", "irreversible_action", "merkle_receipt", "tool_call_complete", "tool_call_start", "vault_seal",),
        contract_version="2026.06.22",
    ),
    "arif_init": ToolContract(
        canonical_name="arif_init",
        axis="identity",
        pipeline_stage="000",
        modes=("init", "light", "resume", "validate", "epoch_open", "epoch_seal", "opt_out", "opt_out_profiling",),
        reversibility=Reversibility.REVERSIBLE,
        blast_radius=BlastRadius.MEDIUM,
        authority_required=Authority.PUBLIC,
        channel=Channel.STABLE,
        floors=("L01", "L11", "L12",),
        risk_tier="medium",
        irreversible=False,
        hold_conditions=("action_is_irreversible_without_human_ack", "actor_unverified_for_authenticated_action", "injection_probability_above_0.85",),
        denial_codes=("CONTRACT_DRIFT", "ENVELOPE_MISSING", "F11_AUTH_MISSING", "F12_INJECTION_DETECTED", "F1_AMANAH_VIOLATION",),
        audit_events=("governance_checkpoint", "state_mutation", "tool_call_complete", "tool_call_start", "vault_receipt",),
        contract_version="2026.06.22",
    ),
    "arif_judge": ToolContract(
        canonical_name="arif_judge",
        axis="judge",
        pipeline_stage="888",
        modes=("judge", "validate", "hold", "rules", "armor", "probe", "notify",),
        reversibility=Reversibility.REVERSIBLE,
        blast_radius=BlastRadius.CIVILIZATIONAL,
        authority_required=Authority.OPERATOR,
        channel=Channel.BETA,
        floors=("L01", "L11", "L13",),
        risk_tier="critical",
        irreversible=False,
        hold_conditions=("action_is_irreversible_without_human_ack", "actor_unverified_for_authenticated_action", "missing_verdict_token", "plan_not_approved", "sovereign_approval_missing_for_irreversible",),
        denial_codes=("CONTRACT_DRIFT", "ENVELOPE_MISSING", "F11_AUTH_MISSING", "F13_SOVEREIGN_OVERRIDE", "F1_AMANAH_VIOLATION",),
        audit_events=("governance_checkpoint", "state_mutation", "tool_call_complete", "tool_call_start", "vault_receipt",),
        contract_version="2026.06.22",
    ),
    "arif_kernel_intercept": ToolContract(
        canonical_name="arif_kernel_intercept",
        axis="judge",
        pipeline_stage="888",
        modes=("intercept",),
        reversibility=Reversibility.REVERSIBLE,
        blast_radius=BlastRadius.CIVILIZATIONAL,
        authority_required=Authority.PUBLIC,
        channel=Channel.BETA,
        floors=("L13",),
        risk_tier="critical",
        irreversible=False,
        hold_conditions=("missing_verdict_token", "plan_not_approved", "sovereign_approval_missing_for_irreversible",),
        denial_codes=("CONTRACT_DRIFT", "ENVELOPE_MISSING", "F13_SOVEREIGN_OVERRIDE", "HUMAN_VETO_REQUIRED", "PLAN_MISSING",),
        audit_events=("governance_checkpoint", "state_mutation", "tool_call_complete", "tool_call_start", "vault_receipt",),
        contract_version="2026.06.22",
    ),
    "arif_measure": ToolContract(
        canonical_name="arif_measure",
        axis="vitality",
        pipeline_stage="777",
        modes=("health", "vitals", "cost", "genius", "psi_le", "omega", "landauer", "topology", "drift",),
        reversibility=Reversibility.REVERSIBLE,
        blast_radius=BlastRadius.LOW,
        authority_required=Authority.PUBLIC,
        channel=Channel.STABLE,
        floors=("L02", "L04",),
        risk_tier="low",
        irreversible=False,
        hold_conditions=("evidence_quality_below_0.95", "output_increases_entropy",),
        denial_codes=("CONTRACT_DRIFT", "ENTROPY_INCREASE", "ENVELOPE_MISSING", "EVIDENCE_INSUFFICIENT", "F2_TRUTH_DEFICIT",),
        audit_events=("tool_call_complete", "tool_call_start",),
        contract_version="2026.06.22",
    ),
    "arif_memory": ToolContract(
        canonical_name="arif_memory",
        axis="trace",
        pipeline_stage="555m",
        modes=("recall", "inspect", "attest", "remember", "promote", "revise", "forget",),
        reversibility=Reversibility.IRREVERSIBLE,
        blast_radius=BlastRadius.MEDIUM,
        authority_required=Authority.PUBLIC,
        channel=Channel.STABLE,
        floors=("L01", "L02", "L04", "L08", "L11", "L12", "L13",),
        risk_tier="medium",
        irreversible=True,
        hold_conditions=("action_is_irreversible_without_human_ack", "actor_unverified_for_authenticated_action", "evidence_quality_below_0.95", "genius_score_below_0.80", "injection_probability_above_0.85",),
        denial_codes=("CONTRACT_DRIFT", "ENTROPY_INCREASE", "ENVELOPE_MISSING", "EVIDENCE_INSUFFICIENT", "F11_AUTH_MISSING",),
        audit_events=("governance_checkpoint", "state_mutation", "tool_call_complete", "tool_call_start", "vault_receipt",),
        contract_version="2026.06.22",
    ),
    "arif_observe": ToolContract(
        canonical_name="arif_observe",
        axis="observe",
        pipeline_stage="111",
        modes=("search", "hybrid_discovery", "ingest", "compass", "atlas", "entropy_dS", "vitals",),
        reversibility=Reversibility.REVERSIBLE,
        blast_radius=BlastRadius.LOW,
        authority_required=Authority.PUBLIC,
        channel=Channel.STABLE,
        floors=("L02", "L07",),
        risk_tier="low",
        irreversible=False,
        hold_conditions=("evidence_quality_below_0.95", "uncertainty_band_outside_0.03_0.05",),
        denial_codes=("CONTRACT_DRIFT", "ENVELOPE_MISSING", "EVIDENCE_INSUFFICIENT", "F2_TRUTH_DEFICIT", "F7_HUMILITY_VIOLATION",),
        audit_events=("tool_call_complete", "tool_call_start",),
        contract_version="2026.06.22",
    ),
    "arif_route": ToolContract(
        canonical_name="arif_route",
        axis="boundary",
        pipeline_stage="555",
        modes=("route",),
        reversibility=Reversibility.REVERSIBLE,
        blast_radius=BlastRadius.LOW,
        authority_required=Authority.PUBLIC,
        channel=Channel.STABLE,
        floors=("L01", "L04", "L10",),
        risk_tier="low",
        irreversible=False,
        hold_conditions=("action_is_irreversible_without_human_ack", "ontology_category_mismatch", "output_increases_entropy",),
        denial_codes=("CONSCIOUSNESS_CLAIM", "CONTRACT_DRIFT", "ENTROPY_INCREASE", "ENVELOPE_MISSING", "F10_ONTOLOGY_VIOLATION",),
        audit_events=("tool_call_complete", "tool_call_start",),
        contract_version="2026.06.22",
    ),
    "arif_seal": ToolContract(
        canonical_name="arif_seal",
        axis="seal",
        pipeline_stage="999",
        modes=("seal", "verify", "ledger", "changelog", "audit",),
        reversibility=Reversibility.IRREVERSIBLE,
        blast_radius=BlastRadius.CIVILIZATIONAL,
        authority_required=Authority.OPERATOR,
        channel=Channel.BETA,
        floors=("L01", "L11", "L13",),
        risk_tier="critical",
        irreversible=True,
        hold_conditions=("action_is_irreversible_without_human_ack", "actor_unverified_for_authenticated_action", "missing_verdict_token", "plan_not_approved", "sovereign_approval_missing_for_irreversible",),
        denial_codes=("CONTRACT_DRIFT", "ENVELOPE_MISSING", "F11_AUTH_MISSING", "F13_SOVEREIGN_OVERRIDE", "F1_AMANAH_VIOLATION",),
        audit_events=("governance_checkpoint", "human_ack_verified", "irreversible_action", "merkle_receipt", "tool_call_complete", "tool_call_start", "vault_seal",),
        contract_version="2026.06.22",
    ),
    "arif_think": ToolContract(
        canonical_name="arif_think",
        axis="reason",
        pipeline_stage="333",
        modes=("reason", "reflect", "verify", "critique", "axioms", "plan", "plan_review", "plan_approve", "refactor_plan", "metabolize",),
        reversibility=Reversibility.REVERSIBLE,
        blast_radius=BlastRadius.MEDIUM,
        authority_required=Authority.PUBLIC,
        channel=Channel.STABLE,
        floors=("L02", "L07", "L08", "L10",),
        risk_tier="medium",
        irreversible=False,
        hold_conditions=("evidence_quality_below_0.95", "genius_score_below_0.80", "ontology_category_mismatch", "uncertainty_band_outside_0.03_0.05",),
        denial_codes=("CONSCIOUSNESS_CLAIM", "CONTRACT_DRIFT", "ENVELOPE_MISSING", "EVIDENCE_INSUFFICIENT", "F10_ONTOLOGY_VIOLATION",),
        audit_events=("reasoning_trace", "tool_call_complete", "tool_call_start",),
        contract_version="2026.06.22",
    ),
    "arif_triage": ToolContract(
        canonical_name="arif_triage",
        axis="boundary",
        pipeline_stage="555",
        modes=("status", "preflight", "triage",),
        reversibility=Reversibility.REVERSIBLE,
        blast_radius=BlastRadius.LOW,
        authority_required=Authority.PUBLIC,
        channel=Channel.STABLE,
        floors=("L04", "L10",),
        risk_tier="low",
        irreversible=False,
        hold_conditions=("ontology_category_mismatch", "output_increases_entropy",),
        denial_codes=("CONSCIOUSNESS_CLAIM", "CONTRACT_DRIFT", "ENTROPY_INCREASE", "ENVELOPE_MISSING", "F10_ONTOLOGY_VIOLATION",),
        audit_events=("tool_call_complete", "tool_call_start",),
        contract_version="2026.06.22",
    ),
}


# ═══════════════════════════════════════════════════════════════════════════════
# VALIDATION FUNCTIONS
# ═══════════════════════════════════════════════════════════════════════════════


@dataclass
class ValidationResult:
    """Result of a contract validation check."""
    valid: bool
    tool_name: str
    denial_code: DenialCode | None = None
    reason: str = ""
    hold_conditions_met: list[str] = field(default_factory=list)


def validate_tool_call(
    tool_name: str,
    mode: str,
    actor_authority: str = "public",
    has_plan: bool = False,
    plan_approved: bool = False,
    has_verdict_token: bool = False,
    has_envelope: bool = False,
) -> ValidationResult:
    """
    Validate a tool call against its contract.
    Returns ValidationResult with denial code if blocked.
    """
    contract = CONTRACT_REGISTRY.get(tool_name)
    if contract is None:
        return ValidationResult(
            valid=False,
            tool_name=tool_name,
            denial_code=DenialCode.CONTRACT_DRIFT,
            reason=f"Tool '{tool_name}' not in contract registry",
        )

    # Check mode
    if not contract.allows_mode(mode):
        return ValidationResult(
            valid=False,
            tool_name=tool_name,
            denial_code=DenialCode.SCHEMA_VALIDATION_FAILED,
            reason=f"Mode '{mode}' not in allowed modes: {contract.modes}",
        )

    # Check envelope
    if not has_envelope:
        return ValidationResult(
            valid=False,
            tool_name=tool_name,
            denial_code=DenialCode.ENVELOPE_MISSING,
            reason="Tool call lacks required kernel envelope",
        )

    # Check authority
    auth = Authority(actor_authority) if actor_authority in Authority.__members__.values() else Authority.PUBLIC
    if not contract.check_authority(auth):
        return ValidationResult(
            valid=False,
            tool_name=tool_name,
            denial_code=DenialCode.AUTHORITY_INSUFFICIENT,
            reason=f"Authority '{actor_authority}' insufficient, requires '{contract.authority_required.value}'",
        )

    # Check plan requirement
    if contract.requires_plan() and not has_plan:
        return ValidationResult(
            valid=False,
            tool_name=tool_name,
            denial_code=DenialCode.PLAN_MISSING,
            reason=f"Channel '{contract.channel.value}' requires approved plan",
        )

    if contract.requires_plan() and has_plan and not plan_approved:
        return ValidationResult(
            valid=False,
            tool_name=tool_name,
            denial_code=DenialCode.PLAN_NOT_APPROVED,
            reason="Plan exists but is not in APPROVED state",
        )

    # Check verdict token for high-risk
    if contract.requires_verdict_token() and not has_verdict_token:
        return ValidationResult(
            valid=False,
            tool_name=tool_name,
            denial_code=DenialCode.VERDICT_TOKEN_MISSING,
            reason="High-risk tool requires judge verdict token",
        )

    return ValidationResult(valid=True, tool_name=tool_name)


def get_contract(tool_name: str) -> ToolContract | None:
    """Get the contract for a tool, or None if not found."""
    return CONTRACT_REGISTRY.get(tool_name)


def list_contracts() -> dict[str, ToolContract]:
    """Return all registered contracts."""
    return dict(CONTRACT_REGISTRY)


def find_orphan_tools(registered_tools: list[str]) -> list[str]:
    """Find tools registered at runtime but missing from contracts."""
    return [t for t in registered_tools if t not in CONTRACT_REGISTRY]


def find_contract_drift(registered_tools: list[str]) -> dict[str, str]:
    """Find tools in contracts but missing from runtime."""
    return {
        name: "contract_exists_but_runtime_missing"
        for name in CONTRACT_REGISTRY
        if name not in registered_tools
    }

