"""
ARIF Transport Airlock — Canonical Transaction Envelope
═══════════════════════════════════════════════════════════

The ONE data structure that crosses the transport-to-kernel boundary.
Every client dialect (ChatGPT, Claude, FastMCP, stdio, raw JSON-RPC, SSE)
is normalized into this envelope before the kernel sees it.

The kernel never sees client dialects. It sees only this.

DITEMPA BUKAN DIBERI — Forged, Not Given.
"""

from __future__ import annotations

import time
import uuid
from dataclasses import dataclass, field, asdict
from enum import Enum
from typing import Any


# ── Classification ──────────────────────────────────────────────────────────

class ActionClass(str, Enum):
    READ = "read"
    WRITE = "write"
    MUTATE = "mutate"
    IRREVERSIBLE = "irreversible"
    GOVERN = "govern"
    FORGE = "forge"
    QUERY = "query"
    PROBE = "probe"
    UNKNOWN = "unknown"


class AuthLevel(str, Enum):
    NONE = "none"
    ANONYMOUS = "anonymous"
    AUTHENTICATED = "authenticated"
    LEASED = "leased"
    SOVEREIGN = "sovereign"


# ── Envelope ────────────────────────────────────────────────────────────────

@dataclass
class CanonicalEnvelope:
    """
    The normalized transaction that crosses transport → kernel.

    Fields:
        trace_id:         End-to-end correlation ID (generated by airlock)
        actor:            Who is asking (human=<id>,agent=<id>,org=<id>)
        intent:           What they want to do (verb + noun)
        evidence:         Supporting context (session_id, memory hashes, etc.)
        authority:        Auth credential + lease ID if any
        action_class:     READ/WRITE/MUTATE/IRREVERSIBLE/GOVERN/FORGE/QUERY/PROBE
        reversibility:    True if reversible, False if irreversible
        session_state:    Opaque transport cursor (Mcp-Session-Id or equivalent)
        protocol_version: MCP protocol version from client
        transport:        Dialect that originated this (stdio, streamable_http, etc.)
        tool_name:        The target arif_* tool
        tool_args:        Arguments for the tool
        client_info:      Client name + version for audit
        ts:               Timestamp of envelope creation
    """
    trace_id: str
    actor: str
    intent: str
    evidence: dict[str, Any]
    authority: dict[str, Any]
    action_class: ActionClass
    reversibility: bool
    session_state: dict[str, Any]
    protocol_version: str
    transport: str
    tool_name: str
    tool_args: dict[str, Any]
    client_info: dict[str, str]

    # Metadata (set by airlock, not by dialect adapter)
    dialect: str = "raw"
    envelope_version: str = "1.0"
    ts: float = field(default_factory=time.time)
    _arif_transport_domain: bool = True  # marker: this is internal, not client-visible

    def to_dict(self) -> dict[str, Any]:
        return {
            "trace_id": self.trace_id,
            "actor": self.actor,
            "intent": self.intent,
            "evidence": self.evidence,
            "authority": self.authority,
            "action_class": self.action_class.value,
            "reversibility": self.reversibility,
            "session_state": self.session_state,
            "protocol_version": self.protocol_version,
            "transport": self.transport,
            "tool_name": self.tool_name,
            "tool_args": self.tool_args,
            "client_info": self.client_info,
            "dialect": self.dialect,
            "envelope_version": self.envelope_version,
            "ts": self.ts,
            "DITEMPA_BUKAN_DIBERI": True,
        }


# ── Airlock Result ──────────────────────────────────────────────────────────

@dataclass
class AirlockResult:
    """
    Result of airlock processing.
    transport_error: None if envelope was produced, else error dict
    envelope: None if transport_error, else CanonicalEnvelope
    dialect_used: Which dialect adapter processed this
    trace_id: Correlation ID even on error (for debugging)
    """
    transport_error: dict[str, Any] | None
    envelope: CanonicalEnvelope | None
    dialect_used: str
    trace_id: str
    ts: float = field(default_factory=time.time)


# ── Helpers ─────────────────────────────────────────────────────────────────

def new_envelope(
    actor: str = "anonymous",
    intent: str = "probe",
    action_class: ActionClass = ActionClass.PROBE,
    reversibility: bool = True,
    transport: str = "unknown",
    tool_name: str = "arif_ping",
    tool_args: dict[str, Any] | None = None,
    protocol_version: str = "2025-11-25",
    session_state: dict[str, Any] | None = None,
    evidence: dict[str, Any] | None = None,
    authority: dict[str, Any] | None = None,
    client_info: dict[str, str] | None = None,
    dialect: str = "internal",
) -> CanonicalEnvelope:
    """Create a new envelope with sensible defaults."""
    return CanonicalEnvelope(
        trace_id=uuid.uuid4().hex[:16],
        actor=actor,
        intent=intent,
        evidence=evidence or {},
        authority=authority or {},
        action_class=action_class,
        reversibility=reversibility,
        session_state=session_state or {},
        protocol_version=protocol_version,
        transport=transport,
        tool_name=tool_name,
        tool_args=tool_args or {},
        client_info=client_info or {"name": "unknown", "version": "0.0"},
        dialect=dialect,
    )
