"""
ARIF Transport Airlock — Canonical Transaction Envelope
═══════════════════════════════════════════════════════════

The ONE data structure that crosses the transport-to-kernel boundary.
Every client dialect (ChatGPT, Claude, FastMCP, stdio, raw JSON-RPC, SSE)
is normalized into this envelope before the kernel sees it.

The kernel never sees client dialects. It sees only this.

DITEMPA BUKAN DIBERI — Forged, Not Given.
"""

from __future__ import annotations

import time
import uuid
from dataclasses import dataclass, field
from enum import Enum
from typing import Any

# ── Classification ──────────────────────────────────────────────────────────


class ActionClass(str, Enum):
    READ = "read"
    WRITE = "write"
    MUTATE = "mutate"
    IRREVERSIBLE = "irreversible"
    GOVERN = "govern"
    FORGE = "forge"
    QUERY = "query"
    PROBE = "probe"
    UNKNOWN = "unknown"

    def __eq__(self, other: Any) -> bool:
        if isinstance(other, str):
            return self.value.lower() == other.lower() or self.name.lower() == other.lower()
        return super().__eq__(other)

    def __hash__(self) -> int:
        return hash(self.value)


class AuthLevel(str, Enum):
    NONE = "none"
    ANONYMOUS = "anonymous"
    AUTHENTICATED = "authenticated"
    LEASED = "leased"
    SOVEREIGN = "sovereign"


# ── Envelope ────────────────────────────────────────────────────────────────


@dataclass
class CanonicalEnvelope:
    """
    The normalized transaction that crosses transport → kernel.

    Fields:
        trace_id:         End-to-end correlation ID (generated by airlock)
        actor:            Who is asking (human=<id>,agent=<id>,org=<id>)
        intent:           What they want to do (verb + noun)
        evidence:         Supporting context (session_id, memory hashes, etc.)
        authority:        Auth credential + lease ID if any
        action_class:     READ/WRITE/MUTATE/IRREVERSIBLE/GOVERN/FORGE/QUERY/PROBE
        reversibility:    True if reversible, False if irreversible
        session_state:    Opaque transport cursor (Mcp-Session-Id or equivalent)
        protocol_version: MCP protocol version from client
        transport:        Dialect that originated this (stdio, streamable_http, etc.)
        tool_name:        The target arif_* tool
        tool_args:        Arguments for the tool
        client_info:      Client name + version for audit
        ts:               Timestamp of envelope creation
    """

    trace_id: str = field(default_factory=lambda: uuid.uuid4().hex[:16])
    actor: str = "anonymous"
    intent: str = ""
    evidence: dict[str, Any] = field(default_factory=dict)
    authority: Any = field(default_factory=dict)
    action_class: ActionClass = field(default_factory=lambda: ActionClass.UNKNOWN)
    reversibility: Any = "REVERSIBLE"
    session_state: dict[str, Any] = field(default_factory=dict)
    protocol_version: str = "2025-11-25"
    transport: str = "unknown"
    tool_name: str = ""
    tool_args: dict[str, Any] = field(default_factory=dict)
    client_info: dict[str, str] = field(default_factory=dict)

    # Metadata (set by airlock, not by dialect adapter)
    dialect: str = "raw"
    envelope_version: str = "1.0"
    ts: float = field(default_factory=time.time)
    _arif_transport_domain: bool = True  # marker: this is internal, not client-visible

    @property
    def normalized_input(self) -> dict[str, Any]:
        """Map tool_args to normalized_input for protocol compliance."""
        return self.tool_args

    @property
    def risk_level(self) -> str:
        """Map action_class to risk_level."""
        return self.action_class.value

    @property
    def requires_hold(self) -> bool:
        """True if the action requires a sovereign confirmation hold."""
        if self.reversibility in ("IRREVERSIBLE", False):
            return True
        return self.action_class in (
            ActionClass.IRREVERSIBLE,
            ActionClass.FORGE,
            ActionClass.GOVERN,
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "trace_id": self.trace_id,
            "actor": self.actor,
            "intent": self.intent,
            "evidence": self.evidence,
            "authority": self.authority,
            "action_class": self.action_class.value
            if hasattr(self.action_class, "value")
            else str(self.action_class),
            "reversibility": self.reversibility,
            "session_state": self.session_state,
            "protocol_version": self.protocol_version,
            "transport": self.transport,
            "tool_name": self.tool_name,
            "tool_args": self.tool_args,
            "client_info": self.client_info,
            "dialect": self.dialect,
            "envelope_version": self.envelope_version,
            "ts": self.ts,
            "normalized_input": self.normalized_input,
            "risk_level": self.risk_level,
            "requires_hold": self.requires_hold,
            "DITEMPA_BUKAN_DIBERI": True,
        }


# ── Airlock Result ──────────────────────────────────────────────────────────


@dataclass
class AirlockResult:
    """
    Result of airlock processing.
    transport_error: None if envelope was produced, else error dict
    envelope: None if transport_error, else CanonicalEnvelope
    dialect_used: Which dialect adapter processed this
    trace_id: Correlation ID even on error (for debugging)
    """

    transport_error: dict[str, Any] | None
    envelope: CanonicalEnvelope | None
    dialect_used: str
    trace_id: str
    ts: float = field(default_factory=time.time)


# ── Helpers ─────────────────────────────────────────────────────────────────


def new_envelope(
    actor: str = "anonymous",
    intent: str = "probe",
    action_class: ActionClass = ActionClass.PROBE,
    reversibility: bool = True,
    transport: str = "unknown",
    tool_name: str = "arif_ping",
    tool_args: dict[str, Any] | None = None,
    protocol_version: str = "2025-11-25",
    session_state: dict[str, Any] | None = None,
    evidence: dict[str, Any] | None = None,
    authority: dict[str, Any] | None = None,
    client_info: dict[str, str] | None = None,
    dialect: str = "internal",
) -> CanonicalEnvelope:
    """Create a new envelope with sensible defaults."""
    return CanonicalEnvelope(
        trace_id=uuid.uuid4().hex[:16],
        actor=actor,
        intent=intent,
        evidence=evidence or {},
        authority=authority or {},
        action_class=action_class,
        reversibility=reversibility,
        session_state=session_state or {},
        protocol_version=protocol_version,
        transport=transport,
        tool_name=tool_name,
        tool_args=tool_args or {},
        client_info=client_info or {"name": "unknown", "version": "0.0"},
        dialect=dialect,
    )


def _classify_method(method: str) -> ActionClass:
    m = method.lower()
    if "ping" in m or "probe" in m or "echo" in m:
        return ActionClass.PROBE
    if "session_init" in m or "initialize" in m:
        return ActionClass.QUERY
    if "forg" in m or "execut" in m or "deploy" in m:
        return ActionClass.FORGE
    if "seal" in m or "judge" in m or "deliberate" in m:
        return ActionClass.GOVERN
    if "write" in m or "create" in m or "update" in m or "delete" in m:
        return ActionClass.IRREVERSIBLE if "delete" in m else ActionClass.MUTATE
    if (
        "read" in m
        or "list" in m
        or "get" in m
        or "query" in m
        or "recall" in m
        or "observe" in m
        or "analyz" in m
        or "status" in m
        or "measure" in m
        or "inspect" in m
        or "attest" in m
        or "version" in m
    ):
        return ActionClass.READ
    return ActionClass.UNKNOWN


def _build_split_session_state(
    request: dict[str, Any],
    mcp_session_id: str | None = None,
    protocol_version: str = "2025-11-25",
    client_capabilities: dict[str, Any] | None = None,
    extra_transport: dict[str, Any] | None = None,
) -> dict[str, Any]:
    if not mcp_session_id:
        mcp_session_id = (
            request.get("_session_id")
            or request.get("mcp_session_id")
            or request.get("session_id")
            or ""
        )
    t_state = {
        "mcp_session_id": mcp_session_id,
        "protocol_version": protocol_version,
        "client_capabilities": client_capabilities or {},
    }
    if extra_transport:
        t_state.update(extra_transport)
    return {
        "transport": t_state,
        "constitutional": {
            "session_id": None,
            "lease_id": None,
            "authority_lease": None,
            "actor_id": None,
            "floor_state": {},
        },
    }
