#!/usr/bin/env python3
"""Generate and verify every public discovery artifact from the Kernel ABI."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from arifosmcp.abi.kernel_abi import (  # noqa: E402
    capability_ids,
    capability_registry,
    profile_contract,
    semantic_tool_names,
    tool_names_for_profile,
    validate_abi,
)
from arifosmcp.runtime.public_registry import build_server_json  # noqa: E402

PROFILE = "public_agent"


def _json(payload: object) -> str:
    return json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def _snapshot() -> dict[str, object]:
    capabilities = capability_registry()["capabilities"]
    selected = set(profile_contract(PROFILE)["capabilities"])
    return {
        "$schema": "arifos://schema/profile-snapshot/v1",
        "abi_version": capability_registry()["abi_version"],
        "profile": PROFILE,
        "kernel_capabilities": list(capability_ids()),
        "kernel_provider_tools": list(semantic_tool_names()),
        "profile_capabilities": [
            item["capability_id"] for item in capabilities if item["capability_id"] in selected
        ],
        "profile_provider_tools": list(tool_names_for_profile(PROFILE)),
        "semantic_hashes": {item["capability_id"]: item["semantic_hash"] for item in capabilities},
    }


def _smithery(server: dict[str, object]) -> str:
    lines = [
        "# Generated by scripts/sync_kernel_abi.py. Do not edit by hand.",
        "name: arifos",
        f'version: "{capability_registry()["abi_version"]}"',
        'display_name: "arifOS — Constitutional Intelligence Kernel"',
        'description: "Platform-neutral governed capability surface."',
        "category: governance",
        "subcategory: ai-safety",
        'mcp_version: "2025-11-25"',
        "transport: streamable_http",
        f"profile: {PROFILE}",
        f"kernel_capability_count: {len(capability_ids())}",
        f"public_tool_count: {len(server['tools'])}",
        "tools:",
    ]
    for tool in server["tools"]:
        lines.extend(
            [
                f"  - id: {tool['name']}",
                f"    name: {tool['name']}",
                f"    description: {json.dumps(tool['description'], ensure_ascii=False)}",
                f"    input_schema: {json.dumps(tool['inputSchema'], sort_keys=True, ensure_ascii=False)}",
            ]
        )
    return "\n".join(lines) + "\n"


def _docs() -> str:
    capabilities = capability_registry()["capabilities"]
    rows = [
        "# Kernel Capability ABI",
        "",
        "> Generated by `scripts/sync_kernel_abi.py`; edit the four registries under `arifosmcp/abi/`.",
        "",
        "arifOS has eight stable semantic capabilities. MCP, REST, A2A, model providers, and UI hosts are adapters; none may redefine capability meaning or grant authority.",
        "",
        "| Capability | Version | MCP binding | Action | Authority |",
        "|---|---:|---|---|---|",
    ]
    for item in capabilities:
        rows.append(
            f"| `{item['capability_id']}` | {item['version']} | `{item['provider']['tool']}` | {item['action_class']} | {item['authority_required']} |"
        )
    rows.extend(
        [
            "",
            "## Profiles",
            "",
            "| Profile | Capabilities | Diagnostics |",
            "|---|---:|---:|",
        ]
    )
    for name in ("public_agent", "trusted_agent", "executor", "sovereign", "operator", "legacy"):
        contract = profile_contract(name)
        rows.append(
            f"| `{name}` | {len(contract['capabilities'])} | {str(contract.get('diagnostics', False)).lower()} |"
        )
    rows.extend(
        [
            "",
            "Compatibility aliases resolve server-side and never appear in discovery. Model identity and transport identity are evidence, not authority.",
            "",
        ]
    )
    return "\n".join(rows)


def expected_files() -> dict[Path, str]:
    abi = validate_abi()
    if not abi["ok"]:
        raise RuntimeError(f"Kernel ABI invalid: {abi['errors']}")
    runtime = build_server_json(surface_mode=PROFILE)
    snapshot = _snapshot()
    selected = set(snapshot["profile_capabilities"])
    tool_contracts = [
        {
            "name": item["provider"]["tool"],
            "capability_id": item["capability_id"],
            "version": item["version"],
            "semantic_hash": item["semantic_hash"],
        }
        for item in capability_registry()["capabilities"]
        if item["capability_id"] in selected
    ]
    server = {
        "$schema": "https://static.modelcontextprotocol.io/schemas/mcp-server-card/v1.json",
        "version": capability_registry()["abi_version"],
        "protocolVersion": "2025-11-25",
        "serverInfo": {
            "name": "ARIFOS MCP",
            "title": "arifOS Constitutional Kernel",
            "version": runtime["version"],
        },
        "description": "Six-tool public profile projected from the eight-capability platform-neutral Kernel ABI.",
        "transport": {"type": "streamable-http", "endpoint": runtime["serverUrl"]},
        "profile": PROFILE,
        "kernel_abi": {
            "version": capability_registry()["abi_version"],
            "capability_count": len(capability_ids()),
        },
        "tools": tool_contracts,
        "tool_count": len(tool_contracts),
        "homepage": runtime["homepage"],
        "source_of_truth": "arifosmcp/abi/capability_registry.json",
    }
    compatibility = {
        "$schema": "https://modelcontextprotocol.io/specification",
        "generated_from": "arifosmcp/abi/capability_registry.json",
        "profile": PROFILE,
        "abi_version": capability_registry()["abi_version"],
        "server_info": {"name": "arifOS MCP", "description": server["description"]},
        "canonical_discovery": {"endpoint": runtime["serverUrl"], "transport": "streamable-http"},
        "kernel_abi": server["kernel_abi"],
        "tools": tool_contracts,
    }
    return {
        ROOT / "static/.well-known/mcp/server.json": _json(server),
        ROOT / "mcp-arifos.json": _json(compatibility),
        ROOT / "smithery.yaml": _smithery(runtime),
        ROOT / "docs/KERNEL_CAPABILITY_ABI.md": _docs(),
        ROOT / "arifosmcp/abi/generated/public_agent.snapshot.json": _json(snapshot),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files drift")
    args = parser.parse_args()
    drift: list[str] = []
    for path, expected in expected_files().items():
        actual = path.read_text(encoding="utf-8") if path.exists() else None
        if actual != expected:
            drift.append(str(path.relative_to(ROOT)))
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(expected, encoding="utf-8")
    if drift and args.check:
        print("Kernel ABI drift: " + ", ".join(drift))
        return 1
    print(
        f"Kernel ABI {'verified' if args.check else 'generated'}: 8 capabilities, {len(tool_names_for_profile(PROFILE))} public tools"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
