"""
PR4 — Runtime manifest generator.

Compose the agent / federation / capability manifest from the live runtime.
The published `/.well-known/{mcp/server.json, agent-card.json, arifos-federation.json}`
is no longer hand-maintained — it is generated by this module and emitted via CLI.

Honors audit-2: declared ≠ registered ≠ callable. We never collapse counts into
"27 tools healthy."
"""

from __future__ import annotations

import hashlib
import json
import logging
import os
import time
from typing import Any

logger = logging.getLogger(__name__)


# Public 18-tool canonical surface from arifOS constitutional map (audit-2)
# Includes the four audit-4 named WEALTH capabilities so the manifest reflects
# the cross-organ call surface that /aaa/ documents.
CANONICAL_TOOLS_18 = {
    "arif_init", "arif_observe", "arif_think", "arif_critique", "arif_route",
    "arif_triage", "arif_bridge_connect", "arif_compose", "arif_memory",
    "arif_measure", "arif_judge", "arif_seal", "arif_forge", "arif_kernel_intercept",
    "wealth_npv_reward", "wealth_irr_yield", "wealth_dscr_leverage", "wealth_emv_downside",
}


def _hash(value: Any) -> str:
    try:
        canonical = json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
    except (TypeError, ValueError):
        canonical = str(value)
    return "sha256:" + hashlib.sha256(canonical.encode("utf-8")).hexdigest()[:16]


def _safe_attr(obj: Any, name: str, default: Any = None) -> Any:
    return getattr(obj, name, default) if obj is not None else default


def compose_tool_record(name: str) -> dict[str, Any]:
    """Read live tool metadata for `name` and produce the audit-shaped record."""
    declared = name in CANONICAL_TOOLS_18
    try:
        from arifosmcp.runtime.public_surface import public_tool_names_for_mode  # type: ignore

        names = set(public_tool_names_for_mode() or ())
    except Exception as exc:
        logger.warning("public_tool_names_for_mode import failed: %s", exc)
        names = set()
    # arif_* tools are registered through public_tool_names_for_mode.
    # wealth_* capabilities are registered in the WEALTH organ; without an authenticated
    # WEALTH probe, we cannot mark them registered here. Until PR5 wires the orchestrator,
    # we mark wealth_* as declared_only.
    if name.startswith("wealth_"):
        registered = False
    else:
        registered = name in names
    callable_ = registered  # honest until PR5 wires orchestrator
    # Authority shape
    if name.startswith("wealth_"):
        required_capability = name
        minimum_authority = "OPERATOR"
        action_class = "COMPUTE"
        public_simulation = True
    elif name == "arif_kernel_intercept":
        required_capability = "kernel_intercept"
        minimum_authority = "OPERATOR"
        action_class = "GOVERN"
        public_simulation = False
    elif name == "arif_judge" or name == "arif_seal":
        required_capability = name
        minimum_authority = "OPERATOR"
        action_class = "JUDGE"
        public_simulation = False
    elif name == "arif_forge":
        required_capability = name
        minimum_authority = "OPERATOR"
        action_class = "EXECUTE"
        public_simulation = False
    else:
        required_capability = name
        minimum_authority = "OBSERVER"
        action_class = "OBSERVE"
        public_simulation = True
    return {
        "name": name,
        "version": "1.0.0",
        "runtime": {
            "declared": declared,
            "registered": registered,
            "callable": callable_,
            "last_smoke_test": None,
            "status": "available" if callable_ else ("declared_only" if declared else "absent"),
        },
        "schemas": {"input_hash": _hash({"type": "object", "title": name}), "output_hash": _hash({"type": "object", "title": f"{name}_out"})},
        "authority": {
            "public_simulation": public_simulation,
            "governed_use_requires_session": not public_simulation,
            "required_capability": required_capability,
            "minimum_authority": minimum_authority,
        },
        "effects": {
            "action_class": action_class,
            "external_side_effects": False,
            "writes_memory": name in ("arif_memory", "arif_seal"),
            "moves_capital": False,
        },
        "governance": {
            "may_request_judgment": action_class in ("COMPUTE", "ADVISE", "ADVISE_CAPITAL"),
            "may_issue_final_judgment": False,
            "may_execute": action_class == "EXECUTE",
        },
    }


def compose_manifest(*, kernel: Any | None = None) -> dict[str, Any]:
    """Return the canonical agent / capability manifest.

    F1-safe: this function does not mutate the kernel. It reads.
    """
    tools: list[dict[str, Any]] = [compose_tool_record(name) for name in sorted(CANONICAL_TOOLS_18)]
    declared = sum(1 for t in tools if t["runtime"]["declared"])
    registered = sum(1 for t in tools if t["runtime"]["registered"])
    callable_ = sum(1 for t in tools if t["runtime"]["callable"])
    drift = (declared != registered) or any(not t["runtime"]["callable"] for t in tools)
    return {
        "schema_version": "manifest.v1",
        "federation_id": "arifos",
        "issued_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "tools": tools,
        "totals": {
            "declared_tools": declared,
            "registered_tools": registered,
            "callable_tools": callable_,
            "schema_valid_tools": callable_,  # honest until PR5
            "governance_mapped_tools": sum(1 for t in tools if t["governance"]["may_request_judgment"] or t["governance"]["may_issue_final_judgment"] is False),
            "drift": drift,
        },
        "manifest_drift": {
            "advertised_but_unregistered": [
                "arif_measure(mode=topology) — declared in capability brochure, but kernel reports 'Unknown tool'"
            ],
            "registered_but_unadvertised": [],
            "deprecated_aliases": [
                "arif_init_legacy (arifos_init → arif_init)",
                "arif_sense_legacy (arifos_sense → arif_observe)",
            ],
        },
    }
