-- ════════════════════════════════════════════════════════════════════════════════
-- Migration: 20260625_001_external_action_receipt.sql
-- PURPOSE: Bridge the "DB = reality" gap for external side-effects
--          (Hostinger VPS, Cloudflare DNS, GitHub, local-FS, future externals)
-- Type: Additive. No existing tables altered.
-- Rollback: DROP TABLE IF EXISTS public.external_action_receipt;
-- Authority: AAA-SUPABASE-RECORD-DOCTRINE v1.0 §3 (Record Type Jurisdiction)
--            + doctrine §3.5 (External action requires approval at TIER_3)
-- Phase: Visibility + testing — RLS permissive (allow-all) per Arif directive 2026-06-25
--         "allow all first for visibility and testing"
--         → Tighten to per-actor RLS after agents stabilize in production mode
-- ════════════════════════════════════════════════════════════════════════════════

-- ── 1. Create the table ─────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.external_action_receipt (
  id                       bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,

  -- Identity
  receipt_id               uuid NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  source_system            text NOT NULL,                 -- 'hostinger' | 'cloudflare' | 'github' | 'local_fs' | 'docker' | 'cron' | 'shell' | ...
  source_subdomain         text,                          -- e.g. 'vps:af-forge', 'dns:arif-fazil.com', 'repo:arifOS', 'path:/root/...'

  -- Action
  action_type              text NOT NULL,                 -- 'vps_restart', 'dns_update', 'pr_merge', 'file_write', 'secret_rotate', etc.
  target                   text NOT NULL,                 -- resource affected (vps_id, zone, repo, file path)
  parameters               jsonb NOT NULL DEFAULT '{}'::jsonb,
  result                   text NOT NULL DEFAULT 'pending'
                           CHECK (result IN ('pending','success','failure','partial','rolled_back')),
  error_message            text,
  external_reference       text,                          -- ID returned by external system (VPS job ID, PR number, commit SHA, etc.)

  -- Provenance / chain
  tool_call_id             text,                          -- back-link to arifosmcp_tool_calls if generated by a tool
  session_id               text,
  trace_id                 text,
  actor_id                 text NOT NULL,                 -- who initiated (agent:openclaw, human:arif, system:cron, ...)
  initiated_by_ref         text,                          -- chain back to actor

  -- Constitutional governance (per doctrine §3.5)
  risk_tier                integer NOT NULL DEFAULT 1
                           CHECK (risk_tier BETWEEN 1 AND 5),
  floor_refs               text[] NOT NULL DEFAULT '{}'::text[],
  ack_irreversible         boolean NOT NULL DEFAULT false,
  approval_ticket_id       text,                          -- FK conceptually to arifosmcp_approval_tickets.ticket_id
  human_ratifier           text,                          -- F13 — 'Muhammad Arif bin Fazil' if approved by sovereign

  -- Integrity
  payload_hash             text NOT NULL,                 -- sha256 of normalized parameters + result
  prev_receipt_hash        text,                          -- chain link to previous external action receipt

  -- Lifecycle
  metadata                 jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at               timestamptz NOT NULL DEFAULT now(),
  updated_at               timestamptz NOT NULL DEFAULT now(),
  completed_at             timestamptz,
  expires_at               timestamptz                    -- TTL — receipts auto-pruned past this (set NULL for permanent)
);

-- ── 2. Indexes for the access patterns we care about ────────────────────────

CREATE INDEX IF NOT EXISTS idx_ear_source_system     ON public.external_action_receipt(source_system);
CREATE INDEX IF NOT EXISTS idx_ear_action_type       ON public.external_action_receipt(action_type);
CREATE INDEX IF NOT EXISTS idx_ear_result            ON public.external_action_receipt(result);
CREATE INDEX IF NOT EXISTS idx_ear_risk_tier         ON public.external_action_receipt(risk_tier);
CREATE INDEX IF NOT EXISTS idx_ear_session           ON public.external_action_receipt(session_id);
CREATE INDEX IF NOT EXISTS idx_ear_trace             ON public.external_action_receipt(trace_id);
CREATE INDEX IF NOT EXISTS idx_ear_tool_call         ON public.external_action_receipt(tool_call_id);
CREATE INDEX IF NOT EXISTS idx_ear_created_at        ON public.external_action_receipt(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ear_floor_refs        ON public.external_action_receipt USING GIN(floor_refs);
CREATE INDEX IF NOT EXISTS idx_ear_approval_ticket   ON public.external_action_receipt(approval_ticket_id)
  WHERE approval_ticket_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_ear_chain             ON public.external_action_receipt(prev_receipt_hash)
  WHERE prev_receipt_hash IS NOT NULL;

-- ── 3. RLS — allow-all for visibility/testing phase ─────────────────────────
-- Doctrine: tighten after agents stabilize in production mode.
-- Phase 1 policy: service_role full, authenticated full, anon blocked.

ALTER TABLE public.external_action_receipt ENABLE ROW LEVEL SECURITY;

-- service_role: full (kernel + adapters write here)
DROP POLICY IF EXISTS ear_service_full ON public.external_action_receipt;
CREATE POLICY ear_service_full
  ON public.external_action_receipt
  FOR ALL TO service_role
  USING (true) WITH CHECK (true);

-- authenticated: full read+insert+update (agents with JWTs log freely)
-- DELETE forbidden — receipts are append-only in spirit
DROP POLICY IF EXISTS ear_authenticated_read ON public.external_action_receipt;
CREATE POLICY ear_authenticated_read
  ON public.external_action_receipt
  FOR SELECT TO authenticated
  USING (true);

DROP POLICY IF EXISTS ear_authenticated_insert ON public.external_action_receipt;
CREATE POLICY ear_authenticated_insert
  ON public.external_action_receipt
  FOR INSERT TO authenticated
  WITH CHECK (true);

DROP POLICY IF EXISTS ear_authenticated_update ON public.external_action_receipt;
CREATE POLICY ear_authenticated_update
  ON public.external_action_receipt
  FOR UPDATE TO authenticated
  USING (true) WITH CHECK (true);

-- anon: blocked (no permissive policy)
-- RLS is enabled with no permissive anon policy = full deny for anon role.

-- ── 4. updated_at maintenance trigger ────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.touch_updated_at_ear()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_ear_touch_updated_at ON public.external_action_receipt;
CREATE TRIGGER trg_ear_touch_updated_at
  BEFORE UPDATE ON public.external_action_receipt
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at_ear();

-- ── 5. Hash integrity trigger — auto-compute payload_hash if not provided ───
-- If caller leaves payload_hash blank, compute from normalized fields.

CREATE OR REPLACE FUNCTION public.compute_ear_payload_hash()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  canonical text;
BEGIN
  IF NEW.payload_hash IS NULL OR NEW.payload_hash = '' THEN
    canonical := COALESCE(NEW.source_system,'') || '|'
              || COALESCE(NEW.action_type,'') || '|'
              || COALESCE(NEW.target,'') || '|'
              || COALESCE(NEW.result,'') || '|'
              || NEW.parameters::text || '|'
              || COALESCE(NEW.external_reference,'') || '|'
              || COALESCE(NEW.actor_id,'') || '|'
              || NEW.created_at::text;
    NEW.payload_hash := encode(digest(canonical, 'sha256'), 'hex');
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_ear_compute_hash ON public.external_action_receipt;
CREATE TRIGGER trg_ear_compute_hash
  BEFORE INSERT ON public.external_action_receipt
  FOR EACH ROW EXECUTE FUNCTION public.compute_ear_payload_hash();

-- ── 6. Self-documentation ────────────────────────────────────────────────────

COMMENT ON TABLE public.external_action_receipt IS
  'External side-effect receipts (Hostinger VPS, Cloudflare DNS, GitHub, local-FS, etc.). '
  'Bridges the "DB = reality" gap for actions that happen outside the arifOS kernel surface. '
  'Doctrine: AAA-SUPABASE-RECORD-DOCTRINE v1.0 §3.5 (external action receipt). '
  'Phase 1: allow-all RLS for visibility. Phase 2 (post-stabilization): per-actor policies. '
  'Authored: 2026-06-25. Reversible: DROP TABLE IF EXISTS public.external_action_receipt;.';

COMMENT ON COLUMN public.external_action_receipt.source_system IS
  'Origin system: hostinger, cloudflare, github, local_fs, docker, cron, shell, etc.';
COMMENT ON COLUMN public.external_action_receipt.action_type IS
  'Verb on the source system: vps_restart, dns_update, pr_merge, file_write, secret_rotate, etc.';
COMMENT ON COLUMN public.external_action_receipt.tool_call_id IS
  'Back-link to arifosmcp_tool_calls.tool_call_id when the external action was triggered by a kernel tool call.';
COMMENT ON COLUMN public.external_action_receipt.payload_hash IS
  'SHA-256 of normalized receipt contents. Auto-computed if not provided.';
COMMENT ON COLUMN public.external_action_receipt.prev_receipt_hash IS
  'Hash chain link — payload_hash of the prior external_action_receipt row for tamper-evidence.';
COMMENT ON COLUMN public.external_action_receipt.human_ratifier IS
  'F13 SOVEREIGN — must be ''Muhammad Arif bin Fazil'' if the action was human-approved.';

-- ════════════════════════════════════════════════════════════════════════════════
-- END MIGRATION 20260625_001_external_action_receipt
-- ════════════════════════════════════════════════════════════════════════════════